### PR TITLE
Refactoring the whole project

### PR DESCRIPTION
**Pull request by ammarfaizi2**

### CODE REVIEW

**Comment by louvian** [comment]
@ammarfaizi2 when will you finish that refactoring?

You are doing a lot of refactoring, again again and again. The progress is unclear, I can't see the point of it. Care to explain?

**Comment by ammarfaizi2** [comment]
@louvian thanks for complaining.

You are right. Due to my stupidity, the progress is unclear.

To be honest. I don't have time to manage it properly. These days, I
only make small changes every time I get the time. I can't wait for it
to go live. But, I am paying attention to code quality, maintainability,
and extendability. That is why I am doing a lot of refactoring. Even the
current result is not that perfect, but I am doing my best to achieve
that.

I admit that my commit messages are not descriptive. They do not explain
the changes I made very well. I should have written more descriptive
commit messages so the other can understand what is going on here. I
think I have got the morals of the story.

I always take your comment to my heart. By that, I will eventually
improve the work from such a complaint.

**Comment by louvian** [comment]
> to go live. But, I am paying attention to code quality, maintainability,
> and extendability. That is why I am doing a lot of refactoring. Even the
> current result is not that perfect, but I am doing my best to achieve
> that.
>

@ammarfaizi2 I'm not sure this is actually relevant for anything any
more, we need to make rules or something like contributing guidelines.

**Comment by ammarfaizi2** [comment]
@louvian Agreed, I am going to make CONTRIBUTING.md file soon.

**Comment by ammarfaizi2** [comment]
I will be maintaining single PR, so I can focus. I am merging this branch (`dev_001_001) to `dev_001`.

**Comment by ammarfaizi2** [comment]
Thanks for your patience BTW.

**Pull request merged**
