### PR TITLE
[GIT PULL] Refactor UDP support

### PR DESCRIPTION
**Pull request by ammarfaizi2**
Hi,

This is the refactored udp_support for TeaVPN2. There are 17 new commits since commit 060ce85b7119b460dca89fbfc0c8bfdca5f6f905 (".github/workflows: fix store artifact").

If anyone has any issues with these being applied, please let me know.

@louvian, others, please review.
```
----------------------------------------------------------------
The following changes since commit 060ce85b7119b460dca89fbfc0c8bfdca5f6f905:

  .github/workflows: fix store artifact (2021-09-11 08:20:34 +0700)

are available in the Git repository at:

  https://github.com/ammarfaizi2/teavpn2-fork udp_support

for you to fetch changes up to 254cfb6975bb28166a2949ef2f5ae7901273f074:

  Merge branch 'dev_001' into udp_support (2021-09-18 09:55:18 +0700)

----------------------------------------------------------------
Ammar Faizi (17):
      udp_server: ignore several message types on handshake process
      net/linux/iface.c: force delete stale route
      client/udp: refactor, no functional changes
      server: remove unused header file includes
      client: refactor, no functional changes
      all: refactoring, no functional changes
      server/linux/udp_epoll: Set thread name for identifier
      client/linux/udp: Fix clang warnings
      server/linux/udp_epoll: Implement zombie reaper thread
      {client,server}/linux/udp: Clean up debug message
      net/linux/iface: Fix clang warning
      server/linux/udp_epoll: Fix `-Werror=maybe-uninitialized`
      server/linux/udp_epoll: Fix `-Werror=unused-result`
      server/linux/udp_epoll: Fix memory leak and potential UAF
      server/linux/udp_epoll: Add notice when closing client connection
      .gitignore: add `/*.patch`
      Merge branch 'dev_001' into udp_support

 .gitignore                                        |   1 +
 src/teavpn2/client/linux.old.dont_use/Makefile    |  20 +++++
 src/teavpn2/client/linux.old.dont_use/udp.c       | 660 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/teavpn2/client/linux.old.dont_use/udp.h       | 108 ++++++++++++++++++++++
 src/teavpn2/client/linux.old.dont_use/udp_epoll.c | 590 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/teavpn2/client/linux/udp.c                    | 297 ++++++++++++++++++++++++++++++++++++------------------------
 src/teavpn2/client/linux/udp.h                    | 133 ++++++++++++++++++++-------
 src/teavpn2/client/linux/udp_epoll.c              | 549 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------
 src/teavpn2/net/linux/iface.c                     |  11 +++
 src/teavpn2/packet.h                              |   3 +-
 src/teavpn2/server/linux/udp.c                    |   7 +-
 src/teavpn2/server/linux/udp.h                    |  27 +++++-
 src/teavpn2/server/linux/udp_epoll.c              | 242 ++++++++++++++++++++++++++++++++++++++++++-------
 src/teavpn2/server/linux/udp_session.c            |   3 -
 14 files changed, 2205 insertions(+), 446 deletions(-)
 create mode 100644 src/teavpn2/client/linux.old.dont_use/Makefile
 create mode 100644 src/teavpn2/client/linux.old.dont_use/udp.c
 create mode 100644 src/teavpn2/client/linux.old.dont_use/udp.h
 create mode 100644 src/teavpn2/client/linux.old.dont_use/udp_epoll.c
```

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
Let me have one extra day for this one.

**Comment by ammarfaizi2** [comment]
Working on this...

So far I have been using it for 2 days, it ran well. I will add "help" command entry for client/server and wire this up to master branch.

**Comment by ammarfaizi2** [comment]
I will send some instructions to test it out this afternoon after finishing some work. Wait for it.

**Comment by ammarfaizi2** [comment]
Ready for merge, I need an approval from at least one person who has write access to write repository.
@louvian, @zeheater, please approve!

**Review by louvian — APPROVED** [review]

**Comment by louvian** [comment]
Approved

**Comment by ammarfaizi2** [comment]
Thanks, I am merging this...

**Comment by louvian** [comment]
Ammar, with no serious objections or outstanding comments, I just approved without detailed review, hope your self-review is solid :)

**Comment by ammarfaizi2** [comment]
@louvian Let's give it a try and see how it goes. So far I am confident with this one, if it is broken, we will revert.

**Pull request merged**
