### PR TITLE
Create client executable, argument parser and config parser

### LINKED ISSUE #10: Create client executable, argument parser and config parser.
Before we go to https://github.com/TeaInside/teavpn2/issues/2 and https://github.com/TeaInside/teavpn2/issues/3.
We should prepare the client first, so we can add TCP and UDP support to both (client and server).

### TODO list for TeaVPN client:
1. Create argument parser.
2. Create config ini parser.
3. Create unit tests and codecov.

### PR DESCRIPTION
**Pull request by ammarfaizi2**
PR to resolve #10

### CODE REVIEW

**Review by louvian — CHANGES_REQUESTED** [review]
Please squash the gcov fixing commits into a single commit.

**Review by louvian — APPROVED** [review]

**Comment by louvian** [comment]
What's next?

**Comment by ammarfaizi2** [comment]
Waiting for @zeheater's approval.

**Review by zeheater — APPROVED** [review]
Done,

**Pull request merged**
