### PR TITLE
[GIT PULL] src/teavpn2/stack.h: Fix wrong stack logic

### PR DESCRIPTION
**Pull request by ammarfaizi2**
The `bt_stack_pop()` was wrong, the increment of `sp` should be
post-increment, not pre-increment.

Extra:
To ensure this won't break again in the future, I created a new
function for assertion when `NDEBUG` macro is defined. The test
function is called `bt_stack_test()`.

Fixes: https://github.com/TeaInside/teavpn2/issues/37
Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
@zeheater @louvian, this pull request fixes https://github.com/TeaInside/teavpn2/issues/37, please approve.

**Review by louvian — APPROVED** [review]

**Comment by louvian** [comment]
Approved!

**Comment by ammarfaizi2** [comment]
> Approved!

Thanks, I am merging this...

**Comment by zeheater** [comment]
> To ensure this won't break again in the future, I created a new
> function for assertion when NDEBUG macro is defined. The test
> function is called bt_stack_test().
Nice.

**Pull request merged**
